export const SELECT_CHAPTER = 'SELECT_CHAPTER';
export const SELECT_HEADING = 'SELECT_HEADING';
export const SELECT_SUBHEADING = 'SELECT_SUBHEADING';
export const RESET_VALUE = 'RESET_VALUE';
export const ADD_CODE = 'ADD_CODE';
export const RESET_ALL = 'RESET_ALL';
